### ISSUE TITLE
Just Curious About RGB wiring of FT813 and ST7701S

### ISSUE THREAD

**Issue by studuino** [blazer82/FT81x_Arduino_Driver#8]
Hi,
Great Library. 
Btw, why are those red and blue color data lines exchanged in the schematic?
![image](https://user-images.githubusercontent.com/2291009/108985151-18182a00-76bf-11eb-8c53-7cb73c103562.png)

**Comment by blazer82** [comment]
Hi and thanks!

The red and blue color signals are switched in order to simplify routing.

You can [see in the code](https://github.com/blazer82/FT81x_Arduino_Driver/blob/690fe9fef78f691fbf7279b5567ab24e6f9900e1/src/FT81x.cpp#L169) that `REG_SWIZZLE` is set to `2` which according to the datasheet of the FT81x switches the R and the B signals:

<img width="855" alt="swizzle" src="https://user-images.githubusercontent.com/949179/108986991-10429080-7693-11eb-9ba2-ce12b75e51a9.png">

Hope that answers your question 😊

**Comment by studuino** [comment]
oh well understood
thanks for the answer.
